package org.plzhelpus.smartcabinet_android

const val GROUP_REF = "group_ref"
const val EMAIL = "email"
const val USER_REF = "user_ref"
const val DESCRIPTION = "description"
const val CABINET_REF = "cabinet_ref"
const val ADMIN_REF = "admin_ref"
const val MEMBER_REF = "member_ref"
const val GROUP_NAME = "group_name"
const val PARTICIPATED_GROUP = "participated_group"
const val OWNER_EMAIL = "owner_email"
const val OWNER_REF = "owner_ref"
const val USERS = "users"
const val GROUPS = "groups"